---
- hosts: localhost
  vars_files:
    - /home/ec2-user/sms_vars.yml
  tasks:
    - name: "Send SMS with Twilio"
      community.general.twilio:
        account_sid: "{{ account_sid }}"
        auth_token: "{{ auth_token }}"
        from_number: "{{ from_number }}"
        to_numbers: "{{ to_numbers }}"
        msg: "Congratulation! Test From Jenkins Automated job is successful"
