---
- hosts: localhost
  vars_files:
    - email_vars.yml
  tasks:
    - name: "Send email to recipients"
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ username }}"
        password: "{{ password }}"
        to: "{{ to }}"
        subject: "Ansible test email"
        body: "This is a test email from Ansible automated with Jenkins! Thanks in Advance!"
      delegate_to: localhost
