---
- hosts: localhost
  vars_files:
    - /home/ec2-user/email_vars.yml
  tasks:
    - name: "Send email to recipients"
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ username }}"
        password: "{{ password }}"
        to: "{{ to }}"
        subject: "Ansible test email"
        body: "Congratulation!! This is a test email from Ansible automated with Jenkins!!"
      delegate_to: localhost
